global:
  scrape_interval: 15s  # 메트릭 수집 주기 (기본값: 1분)

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['43.200.17.139:9292']  # Spring Boot actuator가 열려있는 IP:PORT
